### ISSUE TITLE
Unable to extend a twig template

### ISSUE THREAD

**Issue by babzich** [UnionOfRAD/li3_twig#2]
Hello,

How can we extend a default template. When i try to do like that:

> {% extends '../layout/defaut.html.twig' %}

I get an exception:

> Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Looks like you try to load a template outside configured >directories (../layout/defaut.html.twig) i

Thanks

**Comment by VerifiedToken** [comment]
Hey,

I'm actually experiencing the same issue. I am unable to include a template outside of the current directory. Any luck?
